
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      # For unused methods, check the coverage instead
      # Several methods called dynamically are detected as unused
      UnusedPrivateMethod:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_paths:
- tests/