
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update
    - composer install
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear config-set auto_discover 1; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear channel-update pear.php.net; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install PHP_CodeSniffer; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv rehash; fi;

#before_script:
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;

script:
    - php bin/validate $TRAVIS_PHP_VERSION

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z