
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
    - php bin/check $TRAVIS_PHP_VERSION install

script:
    - php bin/check $TRAVIS_PHP_VERSION

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: 610b1a750407affca18679ecd6797cc5f75afa4ffa69ea293f431ee0dc92af55